# Generated by Django 4.2.30 on 2026-08-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_video_file_alter_lesson_video_url_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='forms_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Simulado (Google Forms)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Material de Estudo em PDF'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Instruções ou Transcrição'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título da Aula / Módulo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Arquivo da Videoaula (Upload PC)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Videoaula (YouTube)'),
        ),
    ]
