# Generated by Django 4.2.30 on 2026-08-10 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_studentgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Colaborador', max_length=150, verbose_name='Cargo')),
                ('direct_manager', models.CharField(blank=True, max_length=150, null=True, verbose_name='Gestor Direto')),
                ('total_hours', models.IntegerField(default=0, verbose_name='Tempo total de plataforma (Horas)')),
                ('weekly_access_days', models.IntegerField(default=0, verbose_name='Dias de acesso na semana atual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
